apiVersion: v1
entries:
  todo-app:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-05T18:55:06.500645+09:00"
    description: Helm chart for Todo App (frontend + backend)
    digest: 57befc8ce6aa9d11de0813aa585bcaaba4f4c8dfc526f19a9fa5b54614e25ac6
    name: todo-app
    type: application
    urls:
    - https://serynel05.github.io/jiyoon/helm-charts/helm-repo/todo-app-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-05T18:55:06.499776+09:00"